name = "telegram-word-masters-cheat-bot-worker"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-11-18"

# [secrets]
# SECRET_BOT_API_TOKEN

[build]
command = "yarn && yarn build"

[build.upload]
format = "service-worker"
