name = "telegram-word-masters-cheat-bot-worker"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-11-18"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
